#!/usr/bin/env python3
"""Generate build-constraints.txt: hash-pinned build dependencies (Phase 11f).

Phase 6/11c pinned the *native* deps; this pins the *Python build* inputs. The
output is an exact-version, SHA256-hashed constraints file covering every wheel /
sdist variant on PyPI for the pinned versions, so a build can be made fully
reproducible and supply-chain-verified:

    PIP_CONSTRAINT=build-constraints.txt python -m build      # or: pip install .

Versions here must satisfy pyproject's build-system.requires. Re-run this when
you bump them. Pins are intentionally separate from build-system.requires so the
sdist stays installable on platforms without a wheel for the exact pinned build
dep (PyPI immutability already prevents version drift; this adds verification).

  python scripts/gen_build_constraints.py
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Exact build-dep versions (must satisfy build-system.requires). Bump as tested.
PINS = {
    "setuptools": "82.0.1",
    "wheel": "0.47.0",
    "Cython": "3.2.6",
    "packaging": "26.2",
}


def hashes(name: str, version: str) -> list[str]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as r:
        data = json.load(r)
    digs = sorted({f["digests"]["sha256"] for f in data.get("urls", [])})
    if not digs:
        raise SystemExit(f"no files found for {name}=={version}")
    return digs


def main() -> int:
    lines = [
        "# Hash-pinned build dependencies for reproducible, verified wheel builds.",
        "# Generated by scripts/gen_build_constraints.py -- do not edit by hand.",
        "# Usage: PIP_CONSTRAINT=build-constraints.txt python -m build",
        "# (covers every PyPI wheel/sdist variant of each pinned version).",
        "",
    ]
    for name, version in PINS.items():
        digs = hashes(name, version)
        print(f"  {name}=={version}: {len(digs)} file hashes", file=sys.stderr)
        entry = f"{name}=={version} \\\n"
        entry += " \\\n".join(f"    --hash=sha256:{h}" for h in digs)
        lines.append(entry)
    (ROOT / "build-constraints.txt").write_text("\n".join(lines) + "\n")
    print(f"wrote {ROOT / 'build-constraints.txt'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
